remove old style local web service and add webpack supprt
voidfunction/SparkEnhancement pull request #4
Opened 2018-01-18 11:27 UTC by voidfunction

2018-01-31 08:24 UTC, XiaofanZhang approved these changes

2018-02-01 10:50 UTC, djlan commented on .vscode/tasks.json
> +            "command": "pm run watch",
>pm run watch [](start = 24, length = 12)

npm run watch?

2018-02-01 10:57 UTC, djlan requested changes
:clock1:

2018-02-01 11:00 UTC, djlan approved these changes
:shipit:

2018-02-01 13:26 UTC, merged